import styled from 'styled-components'
import {
  Containner,
  ArticleInsideContainner,
  ArticlesOfContainner,
} from '/pages/styles'
const ArticleEle = styled.article`
  border: 2px solid #000;
  width: 100%;
  margin-bottom: 8px;
  @media (min-width: 680px) {
    width: 20%;
  }
`
export default function Arts() {
  return (
    <ArticlesOfContainner>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
      <ArticleEle>
        <dl>
          <dt>image</dt>
          <ArticleInsideContainner>
            <dd>タグ</dd>
            <dd>content</dd>
            <dd>author</dd>
            <dd>date</dd>
          </ArticleInsideContainner>
        </dl>
      </ArticleEle>
    </ArticlesOfContainner>
  )
}
